In [73]:
import pandas as pd

# Reading the both csv files
beije = pd.read_csv("beije.csv")
form = pd.read_csv("studying_behavior_form_responses.csv")
form.columns = form.columns.str.strip()
beije.columns=beije.columns.str.strip()

In [74]:
beije_df=pd.DataFrame(beije)
beije_df.head()

  cycle_start   cycle_end
0  28.06.2025  05.07.2025
1  25.07.2025         NaN
2  25.07.2025  31.07.2025
3  25.08.2025  31.08.2025
4  22.09.2025  29.09.2025

In [75]:
form_df=pd.DataFrame(form)
form_df.head()

,date,painkiller_usage,study_hours_daily,exam_period,coffee_consumption
0,01.06.2025,No,05:00:00,No,yes
1,02.06.2025,yes,07:00:00,yes,yes
2,03.06.2025,No,04:00:00,yes,yes
3,04.06.2025,No,08:00:00,yes,yes
4,05.06.2025,No,04:00:00,yes,yes

In [76]:
# Beije tarihleri 
beije['cycle_start'] = pd.to_datetime(beije['cycle_start'], dayfirst=True, errors='coerce')
beije['cycle_end'] = pd.to_datetime(beije['cycle_end'], dayfirst=True, errors='coerce')

#goggle form tarihlerini dayfirst'e göre formatladık
form['date']=pd.to_datetime(form['date'], dayfirst= True, errors='coerce')

#tarihleri kronolojik olarak sıraya soktuk
form=form.sort_values('date')
beije=beije.sort_values('cycle_start')

In [77]:
#beije dosyasını günlük seviyeye genişlettik ki form dosyasıyla tarih eşleştirmesi yapabilelim
#ve de is_period adında bir sütun ekledik
expanded = []

for _, row in beije.iterrows():
    if pd.isna(row['cycle_start']) or pd.isna(row['cycle_end']):
        continue
        
    dates = pd.date_range(start=row['cycle_start'], end=row['cycle_end'])

    for d in dates:
        expanded.append({
            'date': d,
            'is_period': 1 
        })

beije_expanded = pd.DataFrame(expanded)

#beije_expanded ile form'u birleştirdik
df = form.merge(beije_expanded, on='date', how='left')

#period tarihi olmayıp boş kalan is_period satırlarına 0 değerini atadık
df['is_period'] = df['is_period'].fillna(0).astype(int)
df.head(60)

,date,painkiller_usage,study_hours_daily,exam_period,coffee_consumption,is_period
0,2025-06-01,No,05:00:00,No,yes,0
1,2025-06-02,yes,07:00:00,yes,yes,0
2,2025-06-03,No,04:00:00,yes,yes,0
3,2025-06-04,No,08:00:00,yes,yes,0
4,2025-06-05,No,04:00:00,yes,yes,0
5,2025-06-06,No,00:00:00,No,yes,0
6,2025-06-07,No,00:00:00,No,yes,0
7,2025-06-08,yes,00:00:00,No,no,0
8,2025-06-09,No,00:00:00,No,yes,0
9,2025-06-10,yes,00:00:00,No,yes,0
10,2025-06-11,No,00:00:00,No,yes,0
11,2025-06-12,No,00:00:00,No,no,0
12,2025-06-13,No,00:00:00,No,yes,0
13,2025-06-14,No,00:00:00,No,yes,0
14,2025-06-15,yes,00:00:00,No,yes,0
15,2025-06-16,No,00:00:00,No,yes,0
16,2025-06-17,No,00:00:00,No,yes,0
17,2025-06-18,No,00:00:00,No,yes,0
18,2025-06-19,No,00:00:00,No,yes,0
19,2025-06-20,No,00:00:00,No,no,0
20,2025-06-20,No,00:00:00,No,no,0
21,2025-06-21,yes,00:00:00,No,yes,0
22,2025-06-22,yes,00:00:00,No,yes,0
23,2025-06-23,No,00:00:00,No,no,0
24,2025-06-24,No,00:00:00,No,yes,0
25,2025-06-25,No,00:00:00,No,yes,0
26,2025-06-26,No,00:00:00,No,no,0
27,2025-06-27,yes,00:00:00,No,no,0
28,2025-06-27,No,00:00:00,No,yes,0
29,2025-06-28,yes,00:00:00,No,no,1
30,2025-06-29,yes,00:00:00,No,yes,1
31,2025-06-30,No,00:00:00,No,yes,1
32,2025-07-01,No,00:00:00,No,yes,1
33,2025-07-02,No,00:00:00,No,yes,1
34,2025-07-03,No,00:00:00,No,no,1
35,2025-07-04,No,00:00:00,No,yes,1
36,2025-07-05,No,00:00:00,No,yes,1
37,2025-07-06,No,00:00:00,No,no,0
38,2025-07-07,No,00:00:00,No,yes,0
39,2025-07-08,No,01:00:00,No,yes,0
40,2025-07-09,No,00:00:00,No,yes,0
41,2025-07-10,No,02:00:00,No,yes,0
42,2025-07-11,No,02:00:00,No,no,0
43,2025-07-12,No,03:00:00,No,no,0
44,2025-07-13,No,01:00:00,No,no,0
45,2025-07-14,No,03:00:00,No,yes,0
46,2025-07-15,No,00:00:00,No,yes,0
47,2025-07-16,No,01:00:00,No,yes,0
48,2025-07-17,No,02:00:00,No,yes,0
49,2025-07-18,yes,03:45:00,No,yes,0
50,2025-07-19,No,05:30:00,No,yes,0
51,2025-07-20,No,02:35:00,No,no,0
52,2025-07-21,No,03:20:00,No,yes,0
53,2025-07-22,yes,04:42:00,No,yes,0
54,2025-07-23,No,00:00:00,No,no,0
55,2025-07-24,yes,03:50:00,No,no,0
56,2025-07-25,yes,01:00:00,No,no,1
57,2025-07-26,yes,02:30:00,No,no,1
58,2025-07-27,yes,00:00:00,No,no,1
59,2025-07-28,yes,06:45:00,yes,yes,1

In [78]:
#tekrar eden satırlarda en son giirlmiş olan satırı doğru kabul edip diğer girişleri sildik
df = df.drop_duplicates(subset='date', keep='last')
df = df.reset_index(drop=True)

In [79]:
#boş veri girişlerini kontrol ettik
df.isna().sum()

date                  0
painkiller_usage      0
study_hours_daily     0
exam_period           0
coffee_consumption    0
is_period             0
dtype: int64

In [80]:
#boolean değerli olması gereken kolonlardaki girdileri 0 ve 1'lere çevirdik
bool_cols = ['painkiller_usage', 'exam_period', 'coffee_consumption']

for col in bool_cols:
    df[col] = df[col].astype(str).str.lower().str.strip()

mapping = {
    "yes": 1,
    "no": 0,
    "1": 1,
    "0": 0,
    "true": 1,
    "false": 0
}

for col in bool_cols:
    df[col] = df[col].map(mapping)

df.head(20)

,date,painkiller_usage,study_hours_daily,exam_period,coffee_consumption,is_period
0,2025-06-01,0,05:00:00,0,1,0
1,2025-06-02,1,07:00:00,1,1,0
2,2025-06-03,0,04:00:00,1,1,0
3,2025-06-04,0,08:00:00,1,1,0
4,2025-06-05,0,04:00:00,1,1,0
5,2025-06-06,0,00:00:00,0,1,0
6,2025-06-07,0,00:00:00,0,1,0
7,2025-06-08,1,00:00:00,0,0,0
8,2025-06-09,0,00:00:00,0,1,0
9,2025-06-10,1,00:00:00,0,1,0
10,2025-06-11,0,00:00:00,0,1,0
11,2025-06-12,0,00:00:00,0,0,0
12,2025-06-13,0,00:00:00,0,1,0
13,2025-06-14,0,00:00:00,0,1,0
14,2025-06-15,1,00:00:00,0,1,0
15,2025-06-16,0,00:00:00,0,1,0
16,2025-06-17,0,00:00:00,0,1,0
17,2025-06-18,0,00:00:00,0,1,0
18,2025-06-19,0,00:00:00,0,1,0
19,2025-06-20,0,00:00:00,0,0,0

In [ ]:
#günlük çalışma saati verilerini float veri tipine dönüştürüp saat cinsinden yazdık (ör: 3 saat 45 dakika = 3.75)
df['study_hours_daily'] = pd.to_timedelta(df['study_hours_daily'], errors='coerce')
df['study_hours_daily'] = df['study_hours_daily'].dt.total_seconds() / 3600
df['study_hours_daily'] = df['study_hours_daily'].round(2)

#deleting the outliers
df = df[(df['study_hours_daily'] >= 0) & (df['study_hours_daily'] <= 16)]

df[(df['date'] >= "2025-09-10") & (df['date'] <= "2025-11-10")]

,date,painkiller_usage,study_hours_daily,exam_period,coffee_consumption,is_period
101,2025-09-10,0,0.00,0,1,0
102,2025-09-11,0,0.00,0,0,0
103,2025-09-12,0,0.00,0,1,0
104,2025-09-13,0,0.00,0,1,0
106,2025-09-15,0,0.00,0,0,0
107,2025-09-16,0,0.00,0,1,0
108,2025-09-17,0,1.00,0,0,0
109,2025-09-18,0,0.00,0,0,0
110,2025-09-19,1,2.50,0,1,0
111,2025-09-20,0,0.00,0,0,0
112,2025-09-21,1,0.00,0,1,0
113,2025-09-22,1,0.00,0,1,1
114,2025-09-23,1,0.00,0,0,1
115,2025-09-24,1,0.00,0,1,1
116,2025-09-25,0,0.00,0,0,1
117,2025-09-26,0,0.00,0,1,1
118,2025-09-27,0,0.00,0,1,1
119,2025-09-28,0,0.00,0,1,1
120,2025-09-29,1,2.50,0,0,1
121,2025-09-30,0,1.00,0,1,0
122,2025-10-01,0,2.60,0,1,0
123,2025-10-02,0,3.45,0,1,0
124,2025-10-03,1,1.50,0,1,0
125,2025-10-04,0,0.00,0,1,0
126,2025-10-05,0,1.00,0,0,0
127,2025-10-06,0,0.50,0,0,0
128,2025-10-07,0,3.47,0,0,0
129,2025-10-08,0,1.75,0,1,0
130,2025-10-09,1,2.67,0,1,0
131,2025-10-10,0,3.58,0,1,0
132,2025-10-11,0,7.50,0,1,0
133,2025-10-12,0,2.00,0,1,0
134,2025-10-13,1,3.00,0,1,0
135,2025-10-14,0,4.00,0,1,0
136,2025-10-15,0,2.75,0,1,0
137,2025-10-16,1,3.25,0,1,0
138,2025-10-17,0,4.42,0,0,0
139,2025-10-18,0,6.50,0,1,0
140,2025-10-19,0,4.42,0,1,0
141,2025-10-20,1,3.00,0,1,0
142,2025-10-21,0,4.00,0,1,0
143,2025-10-22,1,5.00,0,1,0
144,2025-10-23,1,2.00,0,1,0
145,2025-10-24,0,6.50,0,1,1
146,2025-10-25,0,5.00,0,1,1
147,2025-10-26,0,4.00,0,1,1
148,2025-10-27,0,5.75,0,1,1
149,2025-10-28,1,3.00,0,0,1
150,2025-10-29,0,4.00,0,1,1
151,2025-10-30,1,5.00,0,1,1
152,2025-10-31,0,2.00,0,1,0
153,2025-11-01,0,2.67,0,1,0
154,2025-11-02,0,5.75,0,0,0
156,2025-11-04,1,3.67,1,1,0
157,2025-11-05,0,7.58,1,1,0
158,2025-11-06,1,8.40,1,1,0
159,2025-11-07,1,9.20,1,1,0
160,2025-11-08,1,6.80,1,1,0
161,2025-11-09,1,3.58,1,0,0
162,2025-11-10,0,3.63,0,1,0

In [106]:
#temizlenmiş vetri setini csv olarak kaydediyoruz.
df.to_csv("/Users/berilnurserbest/Desktop/DSA210_Project/data_cleaned.csv", index=False, encoding="utf-8")